target 'Bloomer' do
    platform :ios, '8.0'
    pod 'SocketRocket'
    pod 'DZNPhotoPickerController'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKMessengerShareKit'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'GoogleConversionTracking'
    pod 'FLAnimatedImage'
    pod 'AFNetworking'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'lottie-ios'
end
 
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_ENABLE_OBJC_WEAK'] ||= 'YES'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
        end
    end
end
